api: "1.15"
name: ClueScrollManager
version: "${project.version}"
main: main.ClueScrollManager
api-version: 1.15
author: Izocel
softdepends: [Vault, ClueScrolls]
commands:
  scroll-upgrade:
    description: Used to upgrade scrolls to higher tiers scrolls | <tierName:string> [maxAmount:number default:unlimited]
    usage: /scroll-upgrade 
  scroll-exchange:
    description: Used to exchange scrolls for coins | <tierName:string> [maxAmount:number default:unlimited]
    usage: /scroll-exchange
